version: 2.2.2.{build}
before_build:
- nuget restore Telesign.sln
build:
  project: Telesign.sln
after_test: 
    - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"packages\NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe" -targetargs:"Telesign.Test\bin\Debug\Telesign.Test.dll --noresult" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\coverage.xml
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "coverage.xml"
